### ISSUE TITLE
About the amount of memory required to run the project. 

### ISSUE THREAD

**Issue by RaynorLEE** [chasers-of-Qs/OEILP#1]
Dear Mr. / Ms., 

Thank you very much for sharing the code.
I would like to know how much memory is needed to run the project (create and assess the lmdb) since I am suffering from the following error: 
lmdb.Error: utils\..\data/yago/subgraphs_en_True_neg_1_hop_3: Not enough memory resources are available to process this command.

Your reply will be greatly appreciated.

Regards,
MZ

**Comment by chasers-of-Qs** [comment]
Dear Li,

In our work, all experiments were conducted on a GeForce GTX 2080Ti with 12GB RAM. In practice, running below this memory size will result in insufficient memory resources required for part of the experiments. Therefore, we suggest you run this project on a device with at least no less than 12GB RAM.

Hopefully our response will help you.

Good luck!

**Comment by RaynorLEE** [comment]
Thank you very much.
